spring:
  datasource:
    url: jdbc:mysql://mysql:3306/mojaryba
    username: root
    password: vihNGZezQko4WJ4e
    driver-class-name: com.mysql.cj.jdbc.Driver

  liquibase:
    contexts: prod

  web:
    resources:
      static-locations: classpath:/static/,file:uploads/

app:
  storage:
    location: uploads/photos/
  email:
    url: http://moja-ryba.pl
