spring:
  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:db/changelog/master.xml
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  profiles:
    active: dev

  web:
    resources:
      cache:
        cachecontrol:
          max-age: 30d
          cache-public: true

server:
  servlet:
    session:
      cookie:
        max-age: 7776000
      timeout: 2592000

app:
  email:
    login: matekjava@onet.pl
    password: pass

  storage:
    photo-location: uploads/photos/
    miniature-photo-location: uploads/miniatures/


