spring:
  jpa:
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:db/changelog/master.xml
  servlet:
    multipart:
      max-file-size: 20MB
  profiles:
    active: dev

server:
  servlet:
    session:
      cookie:
        max-age: 7776000
      timeout: 2592000


